export const naiveThemeOverrides = {
  LoadingBar: {
    colorLoading: "#646cff",
  },
  common: {
    errorColor: "#f5222d",
    errorColorActive: "#f5222d1a",
    errorColorHover: "#ff4d4f",
    errorColorPressed: "#cf1322",
    errorColorSuppl: "#f5222d",
    infoColor: "#4a4cd9",
    infoColorActive: "#4a4cd91a",
    infoColorHover: "#7378e6",
    infoColorPressed: "#3634b3",
    infoColorSuppl: "#4a4cd9",
    primaryColor: "#646cff",
    primaryColorActive: "#646cff1a",
    primaryColorHover: "#8c96ff",
    primaryColorPressed: "#4a4cd9",
    primaryColorSuppl: "#646cff",
    successColor: "#52c41a",
    successColorActive: "#52c41a1a",
    successColorHover: "#73d13d",
    successColorPressed: "#389e0d",
    successColorSuppl: "#52c41a",
    warningColor: "#faad14",
    warningColorActive: "#faad141a",
    warningColorHover: "#ffc53d",
    warningColorPressed: "#d48806",
    warningColorSuppl: "#faad14",
  },
};
